### ISSUE TITLE
Dots incorrect replacement in regexp expressions

### ISSUE THREAD

**Issue by andry81** [daddel80/notepadpp-multireplace#43] opened 2024-05-13 10:52 UTC
File:

```txt
# dest: "d:\blabla"
#> c:\test1\test1.aaa|test1.txt.lnk
e:\blabla\|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
e:\blabla\|test2.txt
```

Want to replace to:

```txt
# dest: "d:\blabla"
#> c:\test1\test1.aaa|test1.txt.lnk
c:\test1\test1.aaa|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
c:\test2\test2.bbb|test2.txt
```

The expression:

```csv
1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""",REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1,1,3) == ""#> "" then DESTDIR=string.match(string.sub(CAP1,4,-1),""^(.+)\\\\"") elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= ""#"" and string.len(DESTDIR) > 0 and CAP2 ~= nil then REPLACETO=DESTDIR..""\\\\|""..CAP2 end; cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= ""#"" and string.len(REPLACETO) > 0, REPLACETO)",0,0,1,0,1
```

Result:

```txt
# dest: "d:\blabla"
#> c:\test1\test1.aaa|test1.txt.lnk
c:\test1\test1|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
c:\test2\test2|test2.txt
```

**Comment by daddel80** [comment] 2024-05-13 13:07
Hi andry81,

i found the issue. You have to chaneg the assignemnet of DESTDIR into that:
```code
DESTDIR = string.match(string.sub(CAP1, 4, -1), "^(.+[^\\])\\?")
```

So complete Replace statement should look like this: 
```code
init({DESTDIR="", REPLACETO=""});if CAP1 ~= nil and string.sub(CAP1, 1, 3) == "#> " then    DESTDIR = string.match(string.sub(CAP1, 4, -1), "^(.+[^\\])\\?");elseif CAP1 ~= nil and string.sub(CAP1, 1, 1) ~= "#" and string.len(DESTDIR) > 0 and CAP2 ~= nil then    REPLACETO = DESTDIR .. "\\|" .. CAP2;end;cond(    CAP1 ~= nil and CAP2 ~= nil and     string.len(CAP1) > 0 and string.len(CAP2) > 0 and     string.sub(CAP1, 1, 1) ~= "#" and string.len(REPLACETO) > 0,     REPLACETO);
```

The plugin is supporting these special signs in regex since latest version:
```code
{'\\', '^', '$', '.', '|', '?', '*', '+', '(', ')', '[', ']', '{', '}' }
```
Please check this and let me know!


----------
As these Lua expressions can sometimes become unreadable if they are too complex, it is often better to structure them before copying into Replace. To facilitate this, I have enhanced the Edit Field in the list. It now deletes all line feeds (LF) before copying the text into the Find and Replace field of the list. You can open these Edit fields via the context menu, which you can access by right-clicking on a list entry. However, you need to be aware of the semicolons and spaces before copying. Try this.

```code
init({DESTDIR="", REPLACETO=""});

if CAP1 ~= nil and string.sub(CAP1, 1, 3) == "#> " then
    DESTDIR = string.match(string.sub(CAP1, 4, -1), "^(.+[^\\])\\?");
elseif CAP1 ~= nil and string.sub(CAP1, 1, 1) ~= "#" and string.len(DESTDIR) > 0 and CAP2 ~= nil then
    REPLACETO = DESTDIR .. "\\|" .. CAP2;
end;

cond(
    CAP1 ~= nil and CAP2 ~= nil and 
    string.len(CAP1) > 0 and string.len(CAP2) > 0 and 
    string.sub(CAP1, 1, 1) ~= "#" and string.len(REPLACETO) > 0, 
    REPLACETO
); 
```
It is not released yet but you can download this feature with that build:

```url
https://github.com/daddel80/notepadpp-multireplace/actions/runs/9000173314
```
I hope you find it usefull

**Comment by andry81** [comment] 2024-05-15 07:02
> "^(.+)\\\\"

This is legit expression, why it stops by the dot?

**Comment by andry81** [comment] 2024-05-15 07:26
Seems this is issue in the Lua regexp parser: https://www.mycompiler.io/view/JbGtKVnln5X

Another Lua bullsh*t finding. -.-

**Comment by daddel80** [comment] 2024-05-15 12:35
Hi andry81,

It seems I always need a second look ;-) But now I see the error with the dot. The issue is that Lua pattern matching escapes special characters with the % sign, except for the backslash. This conflicts with the regular expressions masking in Notepad++. I will go ahead and fix this.

Thank you for your patience.

Additionally, you can use this statement without any pattern matching since you are reading the complete line into CAP1. You can also verify this by adding set(CAP1).


```code
init({DESTDIR="", REPLACETO=""});

if CAP1 ~= nil and string.sub(CAP1, 1, 3) == "#> " then
    DESTDIR = string.sub(CAP1, 4, -1);
elseif CAP1 ~= nil and string.sub(CAP1, 1, 1) ~= "#" and string.len(DESTDIR) > 0 and CAP2 ~= nil then
    REPLACETO = DESTDIR .. "\\|" .. CAP2;
end;

cond(
    CAP1 ~= nil and CAP2 ~= nil and 
    string.len(CAP1) > 0 and string.len(CAP2) > 0 and 
    string.sub(CAP1, 1, 1) ~= "#" and string.len(REPLACETO) > 0, 
    REPLACETO
); 
```

I will keep you informed when the next build is ready...

**Comment by daddel80** [comment] 2024-05-15 15:25
Hi andry81,

please tet the following Build:

[Build 405](https://github.com/daddel80/notepadpp-multireplace/actions/runs/9098166862)

Besides, your previous regex ^(.+)\\ was only reading the string up to the last \. The previous error occurred because it didn’t stop at the last \ but at the last dot, which is now fixed.

You can also test it with the string:
```text
#> c:\test1\test1.aaa|test1.txt.lnk
```

and this expresion:
```code
1,"^(.+)$","set(string.match(CAP1, ""^(.+)\\\\""))",0,0,1,0,1
```

**Comment by daddel80** [comment] 2024-05-16 18:26
Hi andry81,

the output should be the following. The last \ should be deleted
```text
#> c:\test1
```

of the text 
```text
#> c:\test1\test1.aaa|test1.txt.lnk
```

with that expression:
```code
1,"^(.+)$","set(string.match(CAP1, ""^(.+)\\\\""))",0,0,1,0,1
```

this is updated in that build:
[Build 406](https://github.com/daddel80/notepadpp-multireplace/actions/runs/9117309713

**Comment by andry81** [comment] 2024-05-17 15:52
Seems it still match the dot.

I've a bit improved the code:

```csv
1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""",REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1,1,3) == ""#> "" then DESTDIR=string.match(string.sub(CAP1,4,-1),""^(.+)\\\\"") elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= ""#"" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then REPLACETO=DESTDIR..""\\\\|""..CAP2 else REPLACETO=nil end; cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= ""#"" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)",0,0,1,0,1
```

As I understand the `REPLACETO` variable still must be resetted in case of no match to avoid accidental replacement. But it reports the error:

```
---------------------------
Use Variables: Syntax Error
---------------------------
[string "function cond(cond, trueVal, falseVal)..."]:8: trueVal cannot be nil
---------------------------
OK   
---------------------------
```

If replace `REPLACETO=nil` by `REPLACETO=""`, then it still has incorrect dot match:

```csv
1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""",REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1,1,3) == ""#> "" then DESTDIR=string.match(string.sub(CAP1,4,-1),""^(.+)\\\\"") elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= ""#"" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then REPLACETO=DESTDIR..""\\\\|""..CAP2 else REPLACETO="""" end; cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= ""#"" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)",0,0,1,0,1
```

Result:

```txt
# dest: "d:\blabla"
#> c:\test1\test1.aaa\|test1.txt.lnk
c:\test1\test1.aaa\|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
c:\test2\test2|test2.txt
```

The last line is replaced to `c:\test2\test2|test2.txt` instead of `c:\test2|test2.txt`.

**Comment by daddel80** [comment] 2024-05-17 17:12
Hi andry81,

I haven't delved deeply into your logic, but if you are looking to achieve this result:

```
# dest: "d:\blabla"
#> c:\test1\test1.aaa|test1.txt.lnk
c:\test1\test1.aaa|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
c:\test2\test2.bbb|test2.txt
```

You can do it with the following statement:

```
init({DESTDIR="", REPLACETO=""});

if CAP1 ~= nil and string.sub(CAP1, 1, 3) == "#> " then
    DESTDIR = string.sub(CAP1, 4, -1);
elseif CAP1 ~= nil and string.sub(CAP1, 1, 1) ~= "#" and string.len(DESTDIR) > 0 and CAP2 ~= nil then
    REPLACETO = DESTDIR .. "|" .. CAP2;
end;

cond(
    CAP1 ~= nil and CAP2 ~= nil and 
    string.len(CAP1) > 0 and string.len(CAP2) > 0 and 
    string.sub(CAP1, 1, 1) ~= "#" and string.len(REPLACETO) > 0, 
    REPLACETO
); 
```

Is this the result you are looking to achieve?

**Comment by andry81** [comment] 2024-05-17 20:26
> Is this the result you are looking to achieve?

```lua
init({DESTDIR="",REPLACETO=""});

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+)\\")
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then
    REPLACETO=DESTDIR.."\\|"..CAP2
else
    REPLACETO=nil
end;

cond(
    CAP1 ~= nil and CAP2 ~= nil and
    string.len(CAP1) > 0 and string.len(CAP2) > 0 and
    string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0,
    REPLACETO
)
```

I've used `REPLACETO=nil`, which is valid Lua expression as said here: https://www.lua.org/pil/2.1.html

> you can assign nil to a global variable to delete it

But instead it raises an error.

If replace to `REPLACETO=""` it does not work as expected, when the `^(.+)\\` is a valid expression but instead it matches a string with the dot as the last character while must not.

**Comment by daddel80** [comment] 2024-05-17 21:37
Hi andry81,

Actually, any value passed to the true or false value part in `cond `cannot be nil, even if the condition doesn't pass it through. In fact, it doesn't matter whether the condition passes the set value for true or not. 
However, it is a good point to avoid unnecessary error messages. I will fine-tune the `cond` statement so that an error will only occur for nil values if the condition tries to push a nil as a replace string.

If you are using "" for REPLACETO your result looks like that:
```
# dest: "d:\blabla"
#> c:\test1\test1.aaa|test1.txt.lnk
c:\test1\|test1.txt
#> c:\test2\test2.bbb|test2.txt.lnk
c:\test2\|test2.txt
```

This is statement with REPLACETO set to "":
```
1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""", REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1, 1, 3) == ""#> "" then     DESTDIR = string.match(string.sub(CAP1, 4, -1), ""^(.+)\\\\"");elseif CAP1 ~= nil and string.sub(CAP1, 1, 1) ~= ""#"" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then     REPLACETO = DESTDIR .. ""\\\\|"" .. CAP2; else     REPLACETO = ""d""; end; cond(    CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1, 1, 1) ~= ""#"" and REPLACETO ~= ""d"" and string.len(REPLACETO) > 0,     REPLACETO);",0,0,1,0,1
```

The filenames like `test1.aaa` and `test2.bbb` are ignored because you are filtering them with the last `\ `using this statement: "^(.+)\\"

I will post a new build with an updated `cond` soon, but setting REPLACETO to nil or "" will not change the result. However, it will avoid error messages for nil set as the true value.

**Comment by andry81** [comment] 2024-05-18 07:19
> This is statement with REPLACETO set to "":

I swear I've copied your last 407 build DLL, but it somehow restored back. Can Notepad++ restore DLL overwrite back while working?

**Comment by daddel80** [comment] 2024-05-18 08:03
Hi andry81,

No, Notepad++ itself does not typically revert or restore DLL files back to a previous state on its own after they have been replaced or updated. Maybe you didn't confirm the Administrator privileges when copying the DLL into the Plugin directory.

**Comment by daddel80** [comment] 2024-05-18 14:14
Hi andry81,

The following build will support nil in the cond statement as long as it is not passed as a replacement string, so your REPLACETO with nil expression will work. However, as I previously said, it will not produce any different output compared to REPLACETO with an empty string "".  [Build 409 ](https://github.com/daddel80/notepadpp-multireplace/actions/runs/9140339441)

**Comment by andry81** [comment] 2024-05-18 18:33
> Maybe you didn't confirm the Administrator privileges when copying the DLL into the Plugin directory.

I've used Total Commander and might be there were a different dialog with the `Skip` button (because of locked DLL) instead of `Overwrite` button.

**Comment by andry81** [comment] 2024-05-19 11:04
> Build 409

The expression `^(.+)\\?` stops by `|` character when should not: https://www.mycompiler.io/view/7BM1NgD5hI3

I know it is not related to this issue, but still another issue.

**Comment by daddel80** [comment] 2024-05-19 14:54
Hi andry81,

i tested it with latest build and it works for me.

Input String will not be changed
`"#> c:\test1\test1.aaa|test1.txt.lnk`

with that statememt:
`1,"^(.+)$","set(string.match(CAP1, ""^(.+)\\\\?""))",0,0,1,0,1`

but for confirmation this is deleting till `|` sign:
`1,"^(.+)$","set(string.match(CAP1, ""^(.+)|""))",0,0,1,0,1`

Please double-check if you are really using build 409. It looks for me like the fixed error. It's always better to delete old DLLs before copying and overwriting them.

**Comment by andry81** [comment] 2024-05-19 15:58
> i tested it with latest build and it works for me.

False alarm, CAP1 already is a half of string without `|` :)

**Closed** 2024-05-19 15:59 UTC
